// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        int32      `json:"id"`
	PostID    int32      `json:"postId"`
	ParentID  *int32     `json:"parentId,omitempty"`
	Content   string     `json:"content"`
	Author    string     `json:"author"`
	CreatedAt string     `json:"createdAt"`
	Children  []*Comment `json:"children"`
}

type Mutation struct {
}

type NewComment struct {
	PostID   int32  `json:"postId"`
	ParentID *int32 `json:"parentId,omitempty"`
	Content  string `json:"content"`
	Author   string `json:"author"`
}

type NewPost struct {
	Title         string `json:"title"`
	Content       string `json:"content"`
	Author        string `json:"author"`
	AllowComments bool   `json:"allowComments"`
}

type Post struct {
	ID            int32      `json:"id"`
	Title         string     `json:"title"`
	Content       string     `json:"content"`
	Author        string     `json:"author"`
	AllowComments bool       `json:"allowComments"`
	CreatedAt     string     `json:"createdAt"`
	Comments      []*Comment `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}
