type Post {
    id: Int!
    title: String!
    content: String!
    author: String!
    allowComments: Boolean!
    createdAt: String!
    comments(first: Int, after: String): [Comment!]!
}

type Comment {
    id: Int!
    postId: Int!
    parentId: Int
    content: String!
    author: String!
    createdAt: String!
    children(first: Int, after: String): [Comment!]!
}

type Query {
    posts: [Post!]!
    post(id: Int!): Post
}

input NewPost {
    title: String!
    content: String!
    author: String!
    allowComments: Boolean
}

input NewComment {
    postId: Int!
    parentId: Int
    content: String!
    author: String!
}

type Mutation {
    createPost(input: NewPost!): Post!
    createComment(input: NewComment!): Comment!
}

type Subscription {
    newComment(postId: Int!): Comment!
}
