package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"fmt"

	"github.com/VladimirMovsesyan/forum/internal/domain/model"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.NewPost) (*model.Post, error) {
	post, err := r.storage.CreatePost(ctx, model.Post{
		Title:         input.Title,
		Content:       input.Content,
		Author:        input.Author,
		AllowComments: *input.AllowComments,
	})
	if err != nil {
		return nil, err
	}

	return post, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.NewComment) (*model.Comment, error) {
	post, err := r.storage.Post(ctx, int(input.PostID))
	if err != nil {
		return nil, err
	}

	if !post.AllowComments {
		return nil, fmt.Errorf("creating comments under this post not allowed")
	}

	comment, err := r.storage.CreateComment(ctx, model.Comment{
		PostID:   input.PostID,
		ParentID: input.ParentID,
		Content:  input.Content,
		Author:   input.Author,
	})
	if err != nil {
		return nil, err
	}

	return comment, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	posts, err := r.storage.Posts(ctx)
	if err != nil {
		return nil, err
	}

	return posts, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id int32) (*model.Post, error) {
	post, err := r.storage.Post(ctx, int(id))
	if err != nil {
		return nil, err
	}

	return post, nil
}

// NewComment is the resolver for the newComment field.
func (r *subscriptionResolver) NewComment(ctx context.Context, postID int32) (<-chan *model.Comment, error) {
	panic(fmt.Errorf("not implemented: NewComment - newComment"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
